ui <- function(request){
  fluidPage(

    titlePanel("Lung Health Premonitions - v2022-0.1.0"),

    sidebarLayout(
      sidebarPanel(h3("Questionnaire"),
        radioButtons(inputId = "gender",
                     label = "What is the gender of the patient?",
                     choices = c("male", "female"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "alcohol_consuming",
                     label = "Is the patient drinking alcohol on the regular basis?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "smoking",
                     label = "What about smoking?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "anxiety",
                     label = "Does the patient experience anxiety on a regular basis?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "peer_pressure",
                     label = "What about peer pressure?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "chronic_disease",
                     label = "Does the patient have a chronic disease?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "fatigue",
                     label = "Is the patient often tired?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "allergy",
                     label = "Does the person have an allergy of any kind?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "wheezing",
                     label = "Is the patient often wheezing?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "coughing",
                     label = "What about coughing?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "shortness_of_breath",
                     label = "Does the patient have a short breath?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "swallowing_difficulties",
                     label = "Does the patient have swallowing difficulties?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "yellow_fingers",
                     label = "Does the patient have yellow fingers?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        radioButtons(inputId = "chest_pain",
                     label = "Does the patient suffer from regular chest pain?",
                     choices = c("yes", "no"),
                     selected = "right",
                     inline = TRUE),
        hr(),
        actionButton(inputId = "make_prediction",
                     label = "Run prediction",
                     icon = icon("play"),
                    ),
      ),

      mainPanel(
        tabsetPanel(
          tabPanel("Smoking", renderPrint("testPrint")),
          tabPanel("Prediction statement", renderPrint("patientOutcome")),
          tabPanel("patients data table", DT::dataTableOutput("mytable")),
        )
      )
    )
  )
}
